"""Copy static assets from site/ into dist/ so rendered pages resolve."""
from __future__ import annotations

import shutil
from pathlib import Path

from . import config
from .config import SITE_OUT, SITE_SRC

# WordPress export dirs referenced by HTML (themes, uploads, plugins, core JS/CSS).
ASSET_DIRS = ("wp-content", "wp-includes")

# Root-level static files from the export (not regenerated by render).
ROOT_STATIC_FILES = (
    "robots.txt",
    "wp-sitemap.xsl",
    "wp-sitemap-index.xsl",
)


def _copy_tree(src: Path, dst: Path) -> int:
    if not src.is_dir():
        return 0
    if config.DRY_RUN:
        count = sum(1 for p in src.rglob("*") if p.is_file())
        print(f"[DRY RUN] Would copy {src.relative_to(SITE_SRC)} -> {dst} ({count} files)")
        return count

    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        shutil.copytree(src, dst, dirs_exist_ok=True)
    else:
        shutil.copytree(src, dst)
    return sum(1 for _ in dst.rglob("*") if _.is_file())


def sync_assets(out_root: Path = SITE_OUT) -> dict[str, int]:
    """Mirror WordPress asset trees and root static files into the deploy output."""
    stats: dict[str, int] = {}

    for name in ASSET_DIRS:
        src = SITE_SRC / name
        dst = out_root / name
        stats[name] = _copy_tree(src, dst)

    copied_root = 0
    for name in ROOT_STATIC_FILES:
        src = SITE_SRC / name
        if not src.is_file():
            continue
        dst = out_root / name
        if config.DRY_RUN:
            print(f"[DRY RUN] Would copy {name}")
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
        copied_root += 1
    stats["root_files"] = copied_root
    _ensure_nojekyll(out_root)

    return stats


def _ensure_nojekyll(out_root: Path) -> None:
    """Tell GitHub Pages to skip Jekyll when deploying from branch."""
    path = out_root / ".nojekyll"
    if config.DRY_RUN:
        print("[DRY RUN] Would write .nojekyll")
        return
    out_root.mkdir(parents=True, exist_ok=True)
    path.touch(exist_ok=True)


def print_sync_report(stats: dict[str, int], out_root: Path = SITE_OUT) -> None:
    total = sum(v for k, v in stats.items() if k != "root_files")
    print(f"Synced assets into {out_root}/")
    for name in ASSET_DIRS:
        print(f"  {name}/  {stats.get(name, 0):,} files")
    if stats.get("root_files"):
        print(f"  root static files  {stats['root_files']}")
    print(f"  total asset files  {total:,}")
